export const MOCK_RECIPES = [
  {
    id: 1,
    title: "Carne Asada",
    image: "https://spoonacular.com/recipeImages/1-556x370.jpg",
    summary: "A delicious grilled beef dish with Mexican spices.",
    extendedIngredients: [
      "2 lbs flank steak",
      "1/4 cup lime juice",
      "3 cloves garlic",
      "1 tbsp olive oil",
      "Salt and pepper",
    ],
    instructions: "Marinate steak, grill 5 minutes per side, slice and serve.",
    cuisine: "mexican",
    readyInMinutes: 25,
    servings: 4,
  },
  {
    id: 2,
    title: "Sushi Rolls",
    image: "https://spoonacular.com/recipeImages/2-556x370.jpg",
    summary: "Classic Japanese sushi rolls with salmon and avocado.",
    extendedIngredients: [
      "2 cups sushi rice",
      "1 sheet nori",
      "Fresh salmon",
      "1 avocado",
    ],
    instructions: "Fill, roll tightly, slice, and serve.",
    cuisine: "japanese",
    readyInMinutes: 45,
    servings: 2,
  },
  {
    id: 3,
    title: "Spaghetti Carbonara",
    image: "https://spoonacular.com/recipeImages/3-556x370.jpg",
    summary: "Creamy pasta with egg, pancetta, and Parmesan.",
    extendedIngredients: [
      "8 oz spaghetti",
      "2 eggs",
      "Parmesan cheese",
      "4 oz pancetta",
    ],
    instructions: "Cook pasta, fry pancetta, mix eggs & cheese, combine.",
    cuisine: "italian",
    readyInMinutes: 20,
    servings: 2,
  },
  {
    id: 4,
    title: "Paneer Tikka",
    image: "https://spoonacular.com/recipeImages/4-556x370.jpg",
    summary: "Indian spiced grilled paneer cubes.",
    extendedIngredients: [
      "Paneer",
      "Yogurt",
      "Tikka masala",
      "Lemon juice",
    ],
    instructions: "Marinate paneer, grill until charred.",
    cuisine: "indian",
    readyInMinutes: 35,
    servings: 3,
  },
  {
    id: 5,
    title: "Crêpes Suzette",
    image: "https://spoonacular.com/recipeImages/5-556x370.jpg",
    summary: "French dessert crêpes with orange-butter sauce.",
    extendedIngredients: ["Flour", "Eggs", "Milk", "Orange liqueur"],
    instructions: "Make thin crêpes, top with orange-butter sauce.",
    cuisine: "french",
    readyInMinutes: 30,
    servings: 4,
  },

  /* ⭐⭐⭐ ADDITIONAL 10 RECIPES BELOW ⭐⭐⭐ */

  {
    id: 6,
    title: "Chicken Tikka Masala",
    image: "https://spoonacular.com/recipeImages/716429-556x370.jpg",
    summary: "Creamy tomato-based Indian curry.",
    extendedIngredients: ["Chicken", "Yogurt", "Tomato sauce", "Garlic", "Garam masala"],
    instructions: "Marinate chicken, cook in creamy tomato sauce.",
    cuisine: "indian",
    readyInMinutes: 50,
    servings: 4,
  },
  {
    id: 7,
    title: "Beef Stir Fry",
    image: "https://spoonacular.com/recipeImages/715538-556x370.jpg",
    summary: "Quick Asian stir-fry with vegetables.",
    extendedIngredients: ["Beef strips", "Soy sauce", "Garlic", "Bell peppers"],
    instructions: "Stir fry beef and vegetables with sauce.",
    cuisine: "asian",
    readyInMinutes: 20,
    servings: 3,
  },
  {
    id: 8,
    title: "Chicken Alfredo",
    image: "https://spoonacular.com/recipeImages/642585-556x370.jpg",
    summary: "Creamy pasta with chicken and Parmesan.",
    extendedIngredients: ["Fettuccine", "Cream", "Parmesan", "Chicken breast"],
    instructions: "Cook pasta, make sauce, stir in chicken.",
    cuisine: "italian",
    readyInMinutes: 30,
    servings: 4,
  },
  {
    id: 9,
    title: "Taco Salad",
    image: "https://spoonacular.com/recipeImages/631803-556x370.jpg",
    summary: "A fresh and crunchy Mexican salad.",
    extendedIngredients: ["Ground beef", "Lettuce", "Tomatoes", "Cheddar", "Tortilla chips"],
    instructions: "Cook beef, assemble salad, top with chips.",
    cuisine: "mexican",
    readyInMinutes: 15,
    servings: 2,
  },
  {
    id: 10,
    title: "Pad Thai",
    image: "https://spoonacular.com/recipeImages/665767-556x370.jpg",
    summary: "Sweet and tangy Thai noodle dish.",
    extendedIngredients: ["Rice noodles", "Shrimp", "Eggs", "Peanuts"],
    instructions: "Stir fry noodles with sauce and toppings.",
    cuisine: "thai",
    readyInMinutes: 40,
    servings: 3,
  },
  {
    id: 11,
    title: "Greek Salad",
    image: "https://spoonacular.com/recipeImages/716627-556x370.jpg",
    summary: "Refreshing salad with feta and olives.",
    extendedIngredients: ["Cucumber", "Tomato", "Feta", "Olives", "Olive oil"],
    instructions: "Chop vegetables, toss with dressing.",
    cuisine: "greek",
    readyInMinutes: 10,
    servings: 2,
  },
  {
    id: 12,
    title: "Ramen Soup",
    image: "https://spoonacular.com/recipeImages/715419-556x370.jpg",
    summary: "Japanese noodle soup in rich broth.",
    extendedIngredients: ["Ramen noodles", "Broth", "Egg", "Pork"],
    instructions: "Simmer broth, cook noodles, assemble bowl.",
    cuisine: "japanese",
    readyInMinutes: 45,
    servings: 2,
  },
  {
    id: 13,
    title: "Falafel Wrap",
    image: "https://spoonacular.com/recipeImages/648279-556x370.jpg",
    summary: "Middle Eastern crispy falafel in pita.",
    extendedIngredients: ["Chickpeas", "Garlic", "Tahini", "Pita bread"],
    instructions: "Blend ingredients, fry falafel, assemble wrap.",
    cuisine: "middle eastern",
    readyInMinutes: 35,
    servings: 2,
  },
  {
    id: 14,
    title: "BBQ Pulled Pork Sandwich",
    image: "https://spoonacular.com/recipeImages/715446-556x370.jpg",
    summary: "Slow-cooked pork with smoky BBQ flavor.",
    extendedIngredients: ["Pork shoulder", "BBQ sauce", "Buns", "Onion"],
    instructions: "Slow cook pork, shred, mix with BBQ sauce.",
    cuisine: "american",
    readyInMinutes: 360,
    servings: 6,
  },
  {
    id: 15,
    title: "Lemon Garlic Salmon",
    image: "https://spoonacular.com/recipeImages/511728-556x370.jpg",
    summary: "Oven-baked salmon with lemon & herbs.",
    extendedIngredients: ["Salmon fillets", "Lemon", "Garlic", "Olive oil"],
    instructions: "Season salmon, bake 12-15 min.",
    cuisine: "american",
    readyInMinutes: 25,
    servings: 2,
  }
];
